"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account_cursor import AccountCursor
globals()['AccountCursor'] = AccountCursor
from ledgerclient.model.account_cursor_response import AccountCursorResponse


class TestAccountCursorResponse(unittest.TestCase):
    """AccountCursorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountCursorResponse(self):
        """Test AccountCursorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountCursorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
