"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.single_object_response import SingleObjectResponse
from ledgerclient.model.stats import Stats
from ledgerclient.model.stats_response_all_of import StatsResponseAllOf
globals()['SingleObjectResponse'] = SingleObjectResponse
globals()['Stats'] = Stats
globals()['StatsResponseAllOf'] = StatsResponseAllOf
from ledgerclient.model.stats_response import StatsResponse


class TestStatsResponse(unittest.TestCase):
    """StatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsResponse(self):
        """Test StatsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
