"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.mapping import Mapping
from ledgerclient.model.mapping_response_all_of import MappingResponseAllOf
from ledgerclient.model.single_object_response import SingleObjectResponse
globals()['Mapping'] = Mapping
globals()['MappingResponseAllOf'] = MappingResponseAllOf
globals()['SingleObjectResponse'] = SingleObjectResponse
from ledgerclient.model.mapping_response import MappingResponse


class TestMappingResponse(unittest.TestCase):
    """MappingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMappingResponse(self):
        """Test MappingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MappingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
