"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.mapping_api import MappingApi  # noqa: E501
from ledgerclient.model.contract import Contract
from ledgerclient.model.mapping import Mapping
from test.test_base import TestBase


class TestMappingApi(TestBase):
    """MappingApi unit test stubs"""

    def setUp(self):
        super().setUp()
        self.api = MappingApi(self.client)  # noqa: E501

    def test_get_mapping(self):
        """Test case for get_mapping

        Get mapping  # noqa: E501
        """
        self.api.get_mapping(self.ledger)

    def test_update_mapping(self):
        """Test case for update_mapping

        Put mapping  # noqa: E501
        """
        self.api.update_mapping(self.ledger, Mapping(
            contracts=[
                Contract({"$gt": ["$balance", 0]})
            ]
        ))
        mapping = self.api.get_mapping(self.ledger)
        self.assertEqual(1, len(mapping.data.contracts))


if __name__ == '__main__':
    unittest.main()
