"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.list_transactions200_response_cursor import ListTransactions200ResponseCursor
globals()['ListTransactions200ResponseCursor'] = ListTransactions200ResponseCursor
from ledgerclient.model.list_transactions200_response import ListTransactions200Response


class TestListTransactions200Response(unittest.TestCase):
    """ListTransactions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListTransactions200Response(self):
        """Test ListTransactions200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListTransactions200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
