"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

from ledgerclient.api.script_api import ScriptApi  # noqa: E501
from ledgerclient.model.script import Script
from test.test_base import TestBase


class TestScriptApi(TestBase):
    """ScriptApi unit test stubs"""

    def setUp(self):
        super().setUp()
        self.api = ScriptApi(self.client)  # noqa: E501

    def test_run_script(self):
        """Test case for run_script

        Execute Numscript  # noqa: E501
        """
        self.api.run_script(self.ledger, Script(
            plain="""
            send [COIN 100] (
              source = @world
              destination = @centralbank
            )
            send [COIN 100] (
              source = @centralbank
              destination = @users:001
            )
            """
        ))

if __name__ == '__main__':
    unittest.main()
