"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account import Account
globals()['Account'] = Account
from ledgerclient.model.account_response_all_of import AccountResponseAllOf


class TestAccountResponseAllOf(unittest.TestCase):
    """AccountResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountResponseAllOf(self):
        """Test AccountResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
