"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0-rc.2
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.ledger_info import LedgerInfo
globals()['LedgerInfo'] = LedgerInfo
from ledgerclient.model.ledger_info_response import LedgerInfoResponse


class TestLedgerInfoResponse(unittest.TestCase):
    """LedgerInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLedgerInfoResponse(self):
        """Test LedgerInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LedgerInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
