"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account_with_volumes_and_balances import AccountWithVolumesAndBalances
globals()['AccountWithVolumesAndBalances'] = AccountWithVolumesAndBalances
from ledgerclient.model.account_response import AccountResponse


class TestAccountResponse(unittest.TestCase):
    """AccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountResponse(self):
        """Test AccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
