"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.mapping import Mapping
globals()['Mapping'] = Mapping
from ledgerclient.model.mapping_response_all_of import MappingResponseAllOf


class TestMappingResponseAllOf(unittest.TestCase):
    """MappingResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMappingResponseAllOf(self):
        """Test MappingResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MappingResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
