"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0-rc.2
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.script_api import ScriptApi  # noqa: E501


class TestScriptApi(unittest.TestCase):
    """ScriptApi unit test stubs"""

    def setUp(self):
        self.api = ScriptApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_run_script(self):
        """Test case for run_script

        Execute a Numscript  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
