"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.migration_info import MigrationInfo
globals()['MigrationInfo'] = MigrationInfo
from ledgerclient.model.ledger_info_storage import LedgerInfoStorage


class TestLedgerInfoStorage(unittest.TestCase):
    """LedgerInfoStorage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLedgerInfoStorage(self):
        """Test LedgerInfoStorage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LedgerInfoStorage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
