"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0-rc.2
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.transactions_api import TransactionsApi  # noqa: E501


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        self.api = TransactionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_metadata_on_transaction(self):
        """Test case for add_metadata_on_transaction

        Set the metadata of a transaction by its ID  # noqa: E501
        """
        pass

    def test_count_transactions(self):
        """Test case for count_transactions

        Count the transactions from a ledger  # noqa: E501
        """
        pass

    def test_create_transaction(self):
        """Test case for create_transaction

        Create a new transaction to a ledger  # noqa: E501
        """
        pass

    def test_create_transactions(self):
        """Test case for create_transactions

        Create a new batch of transactions to a ledger  # noqa: E501
        """
        pass

    def test_get_transaction(self):
        """Test case for get_transaction

        Get transaction from a ledger by its ID  # noqa: E501
        """
        pass

    def test_list_transactions(self):
        """Test case for list_transactions

        List transactions from a ledger  # noqa: E501
        """
        pass

    def test_revert_transaction(self):
        """Test case for revert_transaction

        Revert a ledger transaction by its ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
