"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.contract import Contract
globals()['Contract'] = Contract
from ledgerclient.model.mapping import Mapping


class TestMapping(unittest.TestCase):
    """Mapping unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMapping(self):
        """Test Mapping"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Mapping()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
