"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0-rc.2
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.accounts_balances import AccountsBalances
globals()['AccountsBalances'] = AccountsBalances
from ledgerclient.model.balances_cursor_response_cursor import BalancesCursorResponseCursor


class TestBalancesCursorResponseCursor(unittest.TestCase):
    """BalancesCursorResponseCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalancesCursorResponseCursor(self):
        """Test BalancesCursorResponseCursor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalancesCursorResponseCursor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
