"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.error_code import ErrorCode
from ledgerclient.model.metadata import Metadata
from ledgerclient.model.posting import Posting
from ledgerclient.model.transaction import Transaction
from ledgerclient.model.transaction_commit_error_all_of import TransactionCommitErrorAllOf
globals()['ErrorCode'] = ErrorCode
globals()['Metadata'] = Metadata
globals()['Posting'] = Posting
globals()['Transaction'] = Transaction
globals()['TransactionCommitErrorAllOf'] = TransactionCommitErrorAllOf
from ledgerclient.model.transaction_commit_error import TransactionCommitError


class TestTransactionCommitError(unittest.TestCase):
    """TransactionCommitError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCommitError(self):
        """Test TransactionCommitError"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCommitError()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
