"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.cursor import Cursor
from ledgerclient.model.transaction import Transaction
from ledgerclient.model.transaction_cursor_all_of import TransactionCursorAllOf
globals()['Cursor'] = Cursor
globals()['Transaction'] = Transaction
globals()['TransactionCursorAllOf'] = TransactionCursorAllOf
from ledgerclient.model.transaction_cursor import TransactionCursor


class TestTransactionCursor(unittest.TestCase):
    """TransactionCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCursor(self):
        """Test TransactionCursor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCursor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
