"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.get_account400_response import GetAccount400Response


class TestGetAccount400Response(unittest.TestCase):
    """GetAccount400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccount400Response(self):
        """Test GetAccount400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAccount400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
