"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.get_transaction400_response import GetTransaction400Response


class TestGetTransaction400Response(unittest.TestCase):
    """GetTransaction400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTransaction400Response(self):
        """Test GetTransaction400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTransaction400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
