"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.metadata import Metadata
from ledgerclient.model.post_transaction_script import PostTransactionScript
from ledgerclient.model.posting import Posting
globals()['Metadata'] = Metadata
globals()['PostTransactionScript'] = PostTransactionScript
globals()['Posting'] = Posting
from ledgerclient.model.post_transaction import PostTransaction


class TestPostTransaction(unittest.TestCase):
    """PostTransaction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostTransaction(self):
        """Test PostTransaction"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PostTransaction()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
