"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.assets_balances import AssetsBalances
globals()['AssetsBalances'] = AssetsBalances
from ledgerclient.model.get_balances_aggregated200_response import GetBalancesAggregated200Response


class TestGetBalancesAggregated200Response(unittest.TestCase):
    """GetBalancesAggregated200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBalancesAggregated200Response(self):
        """Test GetBalancesAggregated200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBalancesAggregated200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
