"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account import Account
globals()['Account'] = Account
from ledgerclient.model.accounts_cursor_response_cursor import AccountsCursorResponseCursor


class TestAccountsCursorResponseCursor(unittest.TestCase):
    """AccountsCursorResponseCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountsCursorResponseCursor(self):
        """Test AccountsCursorResponseCursor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountsCursorResponseCursor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
