"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account_with_volumes_and_balances import AccountWithVolumesAndBalances
globals()['AccountWithVolumesAndBalances'] = AccountWithVolumesAndBalances
from ledgerclient.model.get_account200_response import GetAccount200Response


class TestGetAccount200Response(unittest.TestCase):
    """GetAccount200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetAccount200Response(self):
        """Test GetAccount200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetAccount200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
