"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""
import unittest

from ledgerclient import ApiClient, Configuration
from ledgerclient.api.transactions_api import TransactionsApi  # noqa: E501
from ledgerclient.cloud.auth import TokenFetcher, StagingAuthEndpoint, StagingLedgerEndpoint


class TestTransactionsApi(unittest.TestCase):
    """TransactionsApi unit test stubs"""

    def setUp(self):
        fetcher = TokenFetcher(url=StagingAuthEndpoint, token="YjgyY2ZjMDktNjZmYi.OWFhNWNjOGQtMTNlMS")
        config = Configuration()
        config.access_token = fetcher.fetch_token()
        config.host = StagingLedgerEndpoint
        client = ApiClient(config)
        self.api = TransactionsApi(client)  # noqa: E501
        self.ledger = "tirelire-88550a7f"

    def test_list_transactions(self):
        """Test case for list_transactions

        Get all Transactions  # noqa: E501
        """
        self.api.list_transactions(self.ledger)

if __name__ == '__main__':
    unittest.main()
