"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.stats_api import StatsApi  # noqa: E501
from test.test_base import TestBase


class TestStatsApi(TestBase):
    """StatsApi unit test stubs"""

    def setUp(self):
        super().setUp()
        self.api = StatsApi(self.client)  # noqa: E501


    def test_read_stats(self):
        """Test case for read_stats

        Get Stats  # noqa: E501
        """
        stats = self.api.read_stats(self.ledger)
        self.assertEqual(0, stats.data.accounts)
        self.assertEqual(0, stats.data.transactions)

if __name__ == '__main__':
    unittest.main()
