"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.stats_api import StatsApi  # noqa: E501


class TestStatsApi(unittest.TestCase):
    """StatsApi unit test stubs"""

    def setUp(self):
        self.api = StatsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_read_stats(self):
        """Test case for read_stats

        Get statistics from a ledger  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
