"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.accounts_balances import AccountsBalances
globals()['AccountsBalances'] = AccountsBalances
from ledgerclient.model.get_balances200_response_cursor_all_of import GetBalances200ResponseCursorAllOf


class TestGetBalances200ResponseCursorAllOf(unittest.TestCase):
    """GetBalances200ResponseCursorAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBalances200ResponseCursorAllOf(self):
        """Test GetBalances200ResponseCursorAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBalances200ResponseCursorAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
