"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.assets_balances import AssetsBalances
globals()['AssetsBalances'] = AssetsBalances
from ledgerclient.model.accounts_balances import AccountsBalances


class TestAccountsBalances(unittest.TestCase):
    """AccountsBalances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountsBalances(self):
        """Test AccountsBalances"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountsBalances()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
