"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.transaction import Transaction
globals()['Transaction'] = Transaction
from ledgerclient.model.transaction_cursor_all_of import TransactionCursorAllOf


class TestTransactionCursorAllOf(unittest.TestCase):
    """TransactionCursorAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCursorAllOf(self):
        """Test TransactionCursorAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCursorAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
