"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.create_transactions400_response import CreateTransactions400Response


class TestCreateTransactions400Response(unittest.TestCase):
    """CreateTransactions400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTransactions400Response(self):
        """Test CreateTransactions400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTransactions400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
