"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0-rc.2
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.balances_cursor_response_cursor import BalancesCursorResponseCursor
globals()['BalancesCursorResponseCursor'] = BalancesCursorResponseCursor
from ledgerclient.model.balances_cursor_response import BalancesCursorResponse


class TestBalancesCursorResponse(unittest.TestCase):
    """BalancesCursorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBalancesCursorResponse(self):
        """Test BalancesCursorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BalancesCursorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
