"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.single_object_response import SingleObjectResponse


class TestSingleObjectResponse(unittest.TestCase):
    """SingleObjectResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSingleObjectResponse(self):
        """Test SingleObjectResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SingleObjectResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
