"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.config import Config
globals()['Config'] = Config
from ledgerclient.model.config_info import ConfigInfo


class TestConfigInfo(unittest.TestCase):
    """ConfigInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigInfo(self):
        """Test ConfigInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfigInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
