"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.create_transactions200_response_all_of import CreateTransactions200ResponseAllOf
from ledgerclient.model.cursor import Cursor
from ledgerclient.model.list_transactions200_response_cursor_all_of import ListTransactions200ResponseCursorAllOf
from ledgerclient.model.transaction import Transaction
globals()['CreateTransactions200ResponseAllOf'] = CreateTransactions200ResponseAllOf
globals()['Cursor'] = Cursor
globals()['ListTransactions200ResponseCursorAllOf'] = ListTransactions200ResponseCursorAllOf
globals()['Transaction'] = Transaction
from ledgerclient.model.create_transactions200_response import CreateTransactions200Response


class TestCreateTransactions200Response(unittest.TestCase):
    """CreateTransactions200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTransactions200Response(self):
        """Test CreateTransactions200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTransactions200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
