"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.server_api import ServerApi  # noqa: E501
from test.test_base import TestBase


class TestServerApi(TestBase):
    """ServerApi unit test stubs"""

    def setUp(self):
        super().setUp()
        self.api = ServerApi(self.client)  # noqa: E501

    def test_get_info(self):
        """Test case for get_info

        Server Info  # noqa: E501
        """
        self.api.get_info()

if __name__ == '__main__':
    unittest.main()
