"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.cursor import Cursor
from ledgerclient.model.list_transactions200_response_cursor_all_of import ListTransactions200ResponseCursorAllOf
from ledgerclient.model.transaction import Transaction
globals()['Cursor'] = Cursor
globals()['ListTransactions200ResponseCursorAllOf'] = ListTransactions200ResponseCursorAllOf
globals()['Transaction'] = Transaction
from ledgerclient.model.list_transactions200_response_cursor import ListTransactions200ResponseCursor


class TestListTransactions200ResponseCursor(unittest.TestCase):
    """ListTransactions200ResponseCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListTransactions200ResponseCursor(self):
        """Test ListTransactions200ResponseCursor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListTransactions200ResponseCursor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
