"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.stats import Stats
globals()['Stats'] = Stats
from ledgerclient.model.stats_response_all_of import StatsResponseAllOf


class TestStatsResponseAllOf(unittest.TestCase):
    """StatsResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatsResponseAllOf(self):
        """Test StatsResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatsResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
