"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.volumes import Volumes
globals()['Volumes'] = Volumes
from ledgerclient.model.aggregated_volumes import AggregatedVolumes


class TestAggregatedVolumes(unittest.TestCase):
    """AggregatedVolumes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAggregatedVolumes(self):
        """Test AggregatedVolumes"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AggregatedVolumes()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
