"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.errors_enum import ErrorsEnum


class TestErrorsEnum(unittest.TestCase):
    """ErrorsEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorsEnum(self):
        """Test ErrorsEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ErrorsEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
