"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account import Account
from ledgerclient.model.account_response_all_of import AccountResponseAllOf
from ledgerclient.model.single_object_response import SingleObjectResponse
globals()['Account'] = Account
globals()['AccountResponseAllOf'] = AccountResponseAllOf
globals()['SingleObjectResponse'] = SingleObjectResponse
from ledgerclient.model.account_response import AccountResponse


class TestAccountResponse(unittest.TestCase):
    """AccountResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountResponse(self):
        """Test AccountResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
