"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account_with_volumes_and_balances import AccountWithVolumesAndBalances


class TestAccountWithVolumesAndBalances(unittest.TestCase):
    """AccountWithVolumesAndBalances unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountWithVolumesAndBalances(self):
        """Test AccountWithVolumesAndBalances"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AccountWithVolumesAndBalances()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
