"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.config_info import ConfigInfo
from ledgerclient.model.config_info_response_all_of import ConfigInfoResponseAllOf
from ledgerclient.model.single_object_response import SingleObjectResponse
globals()['ConfigInfo'] = ConfigInfo
globals()['ConfigInfoResponseAllOf'] = ConfigInfoResponseAllOf
globals()['SingleObjectResponse'] = SingleObjectResponse
from ledgerclient.model.config_info_response import ConfigInfoResponse


class TestConfigInfoResponse(unittest.TestCase):
    """ConfigInfoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigInfoResponse(self):
        """Test ConfigInfoResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfigInfoResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
