"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.balances_api import BalancesApi  # noqa: E501


class TestBalancesApi(unittest.TestCase):
    """BalancesApi unit test stubs"""

    def setUp(self):
        self.api = BalancesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_balances(self):
        """Test case for get_balances

        Get the balances from a ledger's account  # noqa: E501
        """
        pass

    def test_get_balances_aggregated(self):
        """Test case for get_balances_aggregated

        Get the aggregated balances from selected accounts  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
