"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""
import random
import string
import unittest

from ledgerclient import ApiClient, Configuration


class TestBase(unittest.TestCase):
    def setUp(self):
        self.configuration = Configuration()
        self.configuration.host = "http://localhost:3068"
        self.client = ApiClient(self.configuration)
        self.ledger = ''.join(random.choice(string.digits) for i in range(20))

    def tearDown(self):
        self.client.close()
