"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.transaction import Transaction
globals()['Transaction'] = Transaction
from ledgerclient.model.create_transaction_response import CreateTransactionResponse


class TestCreateTransactionResponse(unittest.TestCase):
    """CreateTransactionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTransactionResponse(self):
        """Test CreateTransactionResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTransactionResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
