"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.ledger_storage import LedgerStorage
globals()['LedgerStorage'] = LedgerStorage
from ledgerclient.model.config import Config


class TestConfig(unittest.TestCase):
    """Config unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfig(self):
        """Test Config"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Config()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
