"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.accounts_balances import AccountsBalances
from ledgerclient.model.cursor import Cursor
from ledgerclient.model.get_balances200_response_cursor_all_of import GetBalances200ResponseCursorAllOf
globals()['AccountsBalances'] = AccountsBalances
globals()['Cursor'] = Cursor
globals()['GetBalances200ResponseCursorAllOf'] = GetBalances200ResponseCursorAllOf
from ledgerclient.model.get_balances200_response_cursor import GetBalances200ResponseCursor


class TestGetBalances200ResponseCursor(unittest.TestCase):
    """GetBalances200ResponseCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBalances200ResponseCursor(self):
        """Test GetBalances200ResponseCursor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBalances200ResponseCursor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
