"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.posting import Posting
globals()['Posting'] = Posting
from ledgerclient.model.transaction_data import TransactionData


class TestTransactionData(unittest.TestCase):
    """TransactionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionData(self):
        """Test TransactionData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
