"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.list_accounts200_response_cursor import ListAccounts200ResponseCursor
globals()['ListAccounts200ResponseCursor'] = ListAccounts200ResponseCursor
from ledgerclient.model.list_accounts200_response import ListAccounts200Response


class TestListAccounts200Response(unittest.TestCase):
    """ListAccounts200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAccounts200Response(self):
        """Test ListAccounts200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAccounts200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
