"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.metadata import Metadata


class TestMetadata(unittest.TestCase):
    """Metadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadata(self):
        """Test Metadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Metadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
