"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.transaction_data import TransactionData
globals()['TransactionData'] = TransactionData
from ledgerclient.model.transactions import Transactions


class TestTransactions(unittest.TestCase):
    """Transactions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactions(self):
        """Test Transactions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Transactions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
