"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.cursor import Cursor
globals()['Cursor'] = Cursor
from ledgerclient.model.create_transactions200_response_all_of import CreateTransactions200ResponseAllOf


class TestCreateTransactions200ResponseAllOf(unittest.TestCase):
    """CreateTransactions200ResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateTransactions200ResponseAllOf(self):
        """Test CreateTransactions200ResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CreateTransactions200ResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
