"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.cursor import Cursor
from ledgerclient.model.cursor_response import CursorResponse
from ledgerclient.model.transaction import Transaction
from ledgerclient.model.transaction_cursor_all_of import TransactionCursorAllOf
globals()['Cursor'] = Cursor
globals()['CursorResponse'] = CursorResponse
globals()['Transaction'] = Transaction
globals()['TransactionCursorAllOf'] = TransactionCursorAllOf
from ledgerclient.model.transaction_list_response import TransactionListResponse


class TestTransactionListResponse(unittest.TestCase):
    """TransactionListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionListResponse(self):
        """Test TransactionListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
