"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.accounts_api import AccountsApi  # noqa: E501


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_metadata_to_account(self):
        """Test case for add_metadata_to_account

        Add metadata to an account  # noqa: E501
        """
        pass

    def test_count_accounts(self):
        """Test case for count_accounts

        Count the accounts from a ledger  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Get account by its address  # noqa: E501
        """
        pass

    def test_list_accounts(self):
        """Test case for list_accounts

        List accounts from a ledger  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
