"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import ledgerclient
from ledgerclient.api.mapping_api import MappingApi  # noqa: E501


class TestMappingApi(unittest.TestCase):
    """MappingApi unit test stubs"""

    def setUp(self):
        self.api = MappingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_mapping(self):
        """Test case for get_mapping

        Get the mapping of a ledger  # noqa: E501
        """
        pass

    def test_update_mapping(self):
        """Test case for update_mapping

        Update the mapping of a ledger  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
