"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.config_info import ConfigInfo
globals()['ConfigInfo'] = ConfigInfo
from ledgerclient.model.config_info_response_all_of import ConfigInfoResponseAllOf


class TestConfigInfoResponseAllOf(unittest.TestCase):
    """ConfigInfoResponseAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testConfigInfoResponseAllOf(self):
        """Test ConfigInfoResponseAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ConfigInfoResponseAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
