"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.log import Log
globals()['Log'] = Log
from ledgerclient.model.logs_cursor_response_cursor import LogsCursorResponseCursor


class TestLogsCursorResponseCursor(unittest.TestCase):
    """LogsCursorResponseCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogsCursorResponseCursor(self):
        """Test LogsCursorResponseCursor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LogsCursorResponseCursor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
