"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0-rc.2
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.errors_enum import ErrorsEnum
from ledgerclient.model.transaction import Transaction
globals()['ErrorsEnum'] = ErrorsEnum
globals()['Transaction'] = Transaction
from ledgerclient.model.script_response import ScriptResponse


class TestScriptResponse(unittest.TestCase):
    """ScriptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScriptResponse(self):
        """Test ScriptResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScriptResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
