"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.get_transaction404_response import GetTransaction404Response


class TestGetTransaction404Response(unittest.TestCase):
    """GetTransaction404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetTransaction404Response(self):
        """Test GetTransaction404Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetTransaction404Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
