"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.contract import Contract


class TestContract(unittest.TestCase):
    """Contract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testContract(self):
        """Test Contract"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Contract()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
