"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.account import Account
from ledgerclient.model.cursor import Cursor
from ledgerclient.model.list_accounts200_response_cursor_all_of import ListAccounts200ResponseCursorAllOf
globals()['Account'] = Account
globals()['Cursor'] = Cursor
globals()['ListAccounts200ResponseCursorAllOf'] = ListAccounts200ResponseCursorAllOf
from ledgerclient.model.list_accounts200_response_cursor import ListAccounts200ResponseCursor


class TestListAccounts200ResponseCursor(unittest.TestCase):
    """ListAccounts200ResponseCursor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAccounts200ResponseCursor(self):
        """Test ListAccounts200ResponseCursor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAccounts200ResponseCursor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
