"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.transaction_commit_error import TransactionCommitError
globals()['TransactionCommitError'] = TransactionCommitError
from ledgerclient.model.transaction_commit_error_response import TransactionCommitErrorResponse


class TestTransactionCommitErrorResponse(unittest.TestCase):
    """TransactionCommitErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCommitErrorResponse(self):
        """Test TransactionCommitErrorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCommitErrorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
