"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.error_code import ErrorCode
globals()['ErrorCode'] = ErrorCode
from ledgerclient.model.transaction_commit_error_all_of import TransactionCommitErrorAllOf


class TestTransactionCommitErrorAllOf(unittest.TestCase):
    """TransactionCommitErrorAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCommitErrorAllOf(self):
        """Test TransactionCommitErrorAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCommitErrorAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
