"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.10.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.metadata import Metadata
globals()['Metadata'] = Metadata
from ledgerclient.model.script import Script


class TestScript(unittest.TestCase):
    """Script unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScript(self):
        """Test Script"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Script()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
