"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.list_accounts400_response import ListAccounts400Response


class TestListAccounts400Response(unittest.TestCase):
    """ListAccounts400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testListAccounts400Response(self):
        """Test ListAccounts400Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ListAccounts400Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
