"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.transaction_cursor import TransactionCursor
globals()['TransactionCursor'] = TransactionCursor
from ledgerclient.model.transaction_cursor_response import TransactionCursorResponse


class TestTransactionCursorResponse(unittest.TestCase):
    """TransactionCursorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionCursorResponse(self):
        """Test TransactionCursorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TransactionCursorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
