"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.6.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.get_balances200_response_cursor import GetBalances200ResponseCursor
globals()['GetBalances200ResponseCursor'] = GetBalances200ResponseCursor
from ledgerclient.model.get_balances200_response import GetBalances200Response


class TestGetBalances200Response(unittest.TestCase):
    """GetBalances200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetBalances200Response(self):
        """Test GetBalances200Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GetBalances200Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
