"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import ledgerclient
from ledgerclient.model.cursor import Cursor
globals()['Cursor'] = Cursor
from ledgerclient.model.cursor_response import CursorResponse


class TestCursorResponse(unittest.TestCase):
    """CursorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCursorResponse(self):
        """Test CursorResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CursorResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
