# coding: utf-8

"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.9.0-rc.11
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ledgerclient
from ledgerclient.model.account import Account
from ledgerclient import configuration


class TestAccount(unittest.TestCase):
    """Account unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
