# coding: utf-8

"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""

import unittest

import ledgerclient
from ledgerclient.model.transactions import Transactions
from ledgerclient import configuration


class TestTransactions(unittest.TestCase):
    """Transactions unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
