# coding: utf-8

"""
    Ledger API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: v1.11.0
    Contact: support@numary.com
    Generated by: https://openapi-generator.tech
"""

from ledgerclient.paths.ledger_transactions_txid_metadata.post import AddMetadataOnTransaction
from ledgerclient.paths.ledger_accounts_address_metadata.post import AddMetadataToAccount
from ledgerclient.paths.ledger_accounts.head import CountAccounts
from ledgerclient.paths.ledger_transactions.head import CountTransactions
from ledgerclient.paths.ledger_transactions.post import CreateTransaction
from ledgerclient.paths.ledger_transactions_batch.post import CreateTransactions
from ledgerclient.paths.ledger_accounts_address.get import GetAccount
from ledgerclient.paths.ledger_balances.get import GetBalances
from ledgerclient.paths.ledger_aggregate_balances.get import GetBalancesAggregated
from ledgerclient.paths.info.get import GetInfo
from ledgerclient.paths.ledger__info.get import GetLedgerInfo
from ledgerclient.paths.ledger_mapping.get import GetMapping
from ledgerclient.paths.ledger_transactions_txid.get import GetTransaction
from ledgerclient.paths.ledger_accounts.get import ListAccounts
from ledgerclient.paths.ledger_logs.get import ListLogs
from ledgerclient.paths.ledger_transactions.get import ListTransactions
from ledgerclient.paths.ledger_stats.get import ReadStats
from ledgerclient.paths.ledger_transactions_txid_revert.post import RevertTransaction
from ledgerclient.paths.ledger_script.post import RunScript
from ledgerclient.paths.ledger_mapping.put import UpdateMapping


class LedgerApi(
    AddMetadataOnTransaction,
    AddMetadataToAccount,
    CountAccounts,
    CountTransactions,
    CreateTransaction,
    CreateTransactions,
    GetAccount,
    GetBalances,
    GetBalancesAggregated,
    GetInfo,
    GetLedgerInfo,
    GetMapping,
    GetTransaction,
    ListAccounts,
    ListLogs,
    ListTransactions,
    ReadStats,
    RevertTransaction,
    RunScript,
    UpdateMapping,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
